### ISSUE TITLE
404 Client Error: Not Found for url

### ISSUE THREAD

**Issue by Kribli-krabli** [idlesign/sponsrdump#2]
papa@papundu:~/Sponsor$ python3 ./sponsrdump.py "https://sponsr.ru/uzhukoffa_lessons/" --title "Урок " --to here/ --prefer-video 640x360 --text-to-video
INFO    : Searching data for https://sponsr.ru/uzhukoffa_lessons/ ...
INFO    : Found articles: 300
INFO    : Start dump using preference: VideoPreference(frame='640x360', sound='best') ...
INFO    : Configuration is loaded from sponsrdump.json ...
WARNING : [1/300 0.3%]  Skipped File 1563 [lessons1.mp3]:
INFO    : [1/300 0.3%]  Downloading File 5367b0ed-8bb3-427a-a12f-70553a3c4b96 [Урок 1.  Введение в историю Древнего мира.mp4]:  ...
Traceback (most recent call last):
  File "/home/papa/Sponsor/./sponsrdump.py", line 666, in <module>
    dumper.dump(
  File "/home/papa/Sponsor/./sponsrdump.py", line 613, in dump
    self._download_file(filepath, dest=dest_filename, prefer_video=prefer_video)
  File "/home/papa/Sponsor/./sponsrdump.py", line 307, in _download_file
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://kinescope.io/5367b0ed-8bb3-427a-a12f-70553a3c4b96/master.mpd

**Comment by Kribli-krabli** [comment]
Can I get the access key on one computer (it has Windows installed), and run the script on a virtual machine with Ubuntu?

**Comment by idlesign** [comment]
> 404 Client Error: Not Found for url: https://kinescope.io/5367b0ed-8bb3-427a-a12f-70553a3c4b96/master.mpd

Hm, can't reproduce 404 for that url, there's xml file.

> Can I get the access key on one computer (it has Windows installed), and run the script on a virtual machine with Ubuntu?

Can't say for sure, didn't try such a thing. But the session sure can be invalidated, so the auth file would need to be updated.

**Comment by idlesign** [comment]
Seems to be fix. Please give it a try.

**Comment by Kribli-krabli** [comment]
Now it`s fine. Thx alot!
